[package]
org = "ballerinax"
name = "aws.lambda"
version = "@toml.version@"
distribution = "2201.11.0"
repository = "https://github.com/ballerina-platform/module-ballerinax-aws.lambda"
license = ["Apache-2.0"]
keywords = ["aws", "lambda", "serverless", "cloud"]

[platform.java21]
graalvmCompatible = true
