[package]
org = "ballerinax"
name = "aws.lambda"
version = "3.3.1"
distribution = "2201.14.0-20260527-050400-74f7e6bf"
repository = "https://github.com/ballerina-platform/module-ballerinax-aws.lambda"
license = ["Apache-2.0"]
keywords = ["Vendor/AWS", "Area/Cloud & Infrastructure", "Type/Connector"]

[platform.java25]
graalvmCompatible = true
